services:
  # Backend Node.js Service
  - type: web
    name: chat-app-backend
    runtime: node
    buildCommand: cd server-js && npm install
    startCommand: cd server-js && node app.js
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: NODE_ENV
        value: production
    healthCheckPath: /

  # Frontend React Static Site
  - type: web
    name: chat-app-frontend
    runtime: static
    buildCommand: cd client-react && npm install && npm run build
    staticPublishPath: ./client-react/dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: chat-app-backend
          envVarKey: RENDER_EXTERNAL_URL
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
